# Generated by Django 3.1.4 on 2020-12-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empployee',
            new_name='Employee',
        ),
    ]
